### ISSUE TITLE
rays not showing

### ISSUE THREAD

**Issue by autodesk-adn** [jeremytammik/forgefader#11]
rays are not showing on some brwose
Chrome update 57 – was working in 56. 

there is also issues on Firefox / opera 
works fine on edge

**Comment by jeremytammik** [comment]
thank you for your interest. i am currently unable to continue maintaining this project. please feel free to fix it as needed and submit a pull request. i will gladly integrate that into the main code stream. alternatively, feel free to grab the current code as is and use it in any way you see fit. it illustrates all the required concepts, and that is its one and only purpose. thank you for your understanding and support!
